#!/usr/bin/env bash

set -e

ACTION="${1:-switch}"

case "$ACTION" in
  boot)
    # build the configuration
    pathToConfig=$(nix-build --no-out-link)

    # install to the system profile
    sudo --preserve-env=NIX_PATH nix-env --profile /nix/var/nix/profiles/system --set "$pathToConfig"

    # rebuild grub entries
    sudo ./grub.sh
  ;;

  test)
    # build the configuration
    pathToConfig=$(nix-build --no-out-link)

    # activate the configuration
    sudo --preserve-env=NIX_PATH "$pathToConfig/activate"
  ;;

  switch)
    # build the configuration
    pathToConfig=$(nix-build --no-out-link)

    # install to the system profile
    sudo --preserve-env=NIX_PATH nix-env --profile /nix/var/nix/profiles/system --set "$pathToConfig"

    # rebuild grub entries
    sudo ./grub.sh

    # activate the configuration
    sudo --preserve-env=NIX_PATH "$pathToConfig/activate"
  ;;

  *)
    echo "$0 boot|test|switch"
  ;;
esac


